name: Multi-Task Workflow

on:
  push:
    branches:
      - main

jobs:
  # Job A - Independent task
  job-a:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Task A - List files
        run: |
          echo "Running Task A"
          ls -la

  # Job B - Depends on Job A
  job-b:
    runs-on: ubuntu-latest
    needs: job-a  # Wait for job-a to complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Task B - Display system info
        run: |
          echo "Running Task B"
          uname -a

  # Job C - Depends on Job B
  job-c:
    runs-on: ubuntu-latest
    needs: job-b  # Wait for job-b to complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Task C - Show current directory
        run: |
          echo "Running Task C"
          pwd
